### ISSUE TITLE
MCSM 控制台无法正常显示二维码 （可能面板服无法正常使用）

### ISSUE THREAD

**Issue by yqs112358** [yanhy2000/QBotForLiteloader#1]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37969157/184521131-b2083d96-be39-4370-b018-36168a452b46.png">
如图

**Comment by yanhy2000** [comment]
收到，由于二维码生成是由oicq框架发起，因此准备新增二维码显示方式以适应更多终端，目前进展如下：
- 由于tx扫码登陆策略仅现在支持手机电脑同一个IP才可以登陆，如果使用扫码建议在本地扫码登陆后再上传，因此二维码登陆修复暂时延后；
- 密码登陆正在修复，推荐使用修复后的密码登陆，稳定且长期登陆

**Comment by yqs112358** [comment]
大佬辛苦🥰

**Comment by yanhy2000** [comment]
嗯，经测试mcsm8版本输出确实有古怪，重新生成二维码也输出异常，解决方法如下：
- 升级至mcsm9
- 使用密码登陆
- 等待大佬修补...
