### ISSUE TITLE
将QQ表情“/汪汪”识别为指令

### ISSUE THREAD

**Issue by oftx** [yanhy2000/QBotForLiteloader#2]
如题，希望修复

**Comment by yanhy2000** [comment]
可以检查一下是否在配置文件内把指令前缀触发修改为"/"，表情导致的"/"指令误触发暂时先不维护（主要是自己近期没空），大概解决思路为判断指令后是否为中文，但缺点是一些中文指令的插件将无法转发指令，暂时不维护，建议尝试将指令前缀修改为//或者其他内容
