### ISSUE TITLE
第二次启动时出现错误

### ISSUE THREAD

**Issue by Kupars** [yanhy2000/QBotForLiteloader#4]
19:25:12 INFO [LiteLoader] 3 个 Js 插件已加载。
19:25:12 INFO [LiteLoader] 加载 Node.js 插件...
[2023-01-23T19:25:13.563] [INFO] default - [QBot] ==========开始加载GBot机器人==========
[2023-01-23T19:25:13.568] [INFO] default - [QBot] 检测配置文件存在，准备启动BOT...
undefined:1
﻿{
^

SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at node:embedder_main_0:195:17
    at node:embedder_main_0:405:3
19:25:13 INFO [LiteLoader] NodeJs plugin QBot exited.
19:25:13 ERROR [LiteLoader] Fail to load plugins/nodejs\QBot!
19:25:13 INFO [LiteLoader] 0 个 Node.js 插件已加载。

**Comment by yanhy2000** [comment]
插件太久未更新，新版ll会加载失败。春节后有计划对该插件进行大更新，还请稍等

**Comment by yanhy2000** [comment]
新版本已经发布，可以更新试试看，配置文件需要重新生成

**Comment by Kupars** [comment]
好的，感谢回复

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年1月26日 18:35
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [yanhy2000/QBotForLiteloader] 第二次启动时出现错误 (Issue #4)


新版本已经发布，可以更新试试看，配置文件需要重新生成

―
