### ISSUE TITLE
希望可以增加服->群的消息转发前缀的设置功能

### ISSUE THREAD

**Issue by yqs112358** [yanhy2000/QBotForLiteloader#5]
RT，目前只有设置群->服前缀，另一个方向貌似缺失
有时候服里聊天太多，导致Q群消息太多刷屏，如果能设置前缀就会比较不错
（onChat监听里面加一行.startsWith判断的事）

**Comment by yanhy2000** [comment]
已增加该功能
[https://github.com/yanhy2000/QBotForLiteloader/releases/tag/v0.7](url)

**Comment by yqs112358** [comment]
大佬辛苦
配置文件需要手动处理吗，还是会自动更新添加新的字段

**Comment by yanhy2000** [comment]
如果不嫌麻烦建议先移出来重新生成，也可以手动修改，其中"useGroupBot" 、“qq” 、“bds”内有所变化需要留意
`{
	"useGroupBot": false,
	"qq": {
		"myGroup": 123123,
		"admin": [
			123123
		],
		"BotAccount": 123123,
		"password": ""
	},
	"bds": {
		"ServerChat": 1,
		"GroupChat": 2,
		"ServerChat_prefix": "c",
		"GroupChat_prefix": "chat",
		"ServerEvent": true,
		"group_cmd": true,
		"private_cmd": true,
		"cmd_prefix": "cmd",
		"motd": true,
		"motd_cmd": "查服"
	},
//xxxxxxx
}`

**Comment by yanhy2000** [comment]
配置文件详细说明可看readme，每次更新都会修正readme

**Comment by yqs112358** [comment]
行（
