### ISSUE TITLE
登录时提示QQ版本低

### ISSUE THREAD

**Issue by Kupars** [yanhy2000/QBotForLiteloader#6]
![IMG_20230129_162735](https://user-images.githubusercontent.com/59685042/215314587-ed9515c9-dbf2-4309-9597-22c383c431c0.jpg)
登录时出现此提示，使用yoyorobot也是这个问题，请问这是什么原因造成的TAT

**Comment by yanhy2000** [comment]
QQ版本过低\设备锁验证后网络错误\版本错误等大致解决方法:
1. 尝试在自己电脑上登陆，删除/plugins/QBot/bot_data文件夹多次尝试
2. 更换QQ账号后尝试(本人该方法成功，更换一次)
3. 找以前能登陆QBot插件的数据文件`device-xxxxxx.json`替换到'/plugins/QBot/bot_data/账号/device-xxxxx.json'，并更改xxx为当前账号
4. 更换电脑网络环境如手机热点再次尝试
5. 修改高级配置文件"plugins/QBot/Advanced_Config.json"，将`platform:2`修改为其他试试看：`1:安卓手机 2:aPad 3:安卓手表 4:MacOS 5:iPad`  （修改平台不影响使用QBot，如修改为手表可能会接收不到"戳一戳",但是本项目并未使用到）
6. 使用下面提供的JSON进行手动修改(不推荐，可能无效；临时登陆成功后可删除重新生成)
`{
  "--begin--": "该设备由账号作为seed固定生成，账号不变则永远相同",
  "product": "MRS4S",
  "device": "HIM188MOE",
  "board": "MIRAI-YYDS",
  "brand": "OICQX",
  "model": "Konata 2020",
  "wifi_ssid": "TP-LINK-dsff18e6",
  "bootloader": "U-boot",
  "android_id": "OICQX.54464248.1183",
  "boot_id": "d4c0f876-24c6-4217-dd94-cbb166ee3358",
  "proc_version": "Linux version 4.19.71-9414 (konata@takayama.github.com)",
  "mac_address": "00:52:42:17:DD:91",
  "ip_address": "10.0.203.177",
  "imei": "355503083610752",
  "incremental": 1726886744,
  "--end--": "修改后可能需要重新验证设备"
}`
